import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Services Project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p >
          Get started by editing{' '}
        </p>
      </main>
    </div>
  )
}
